# Generated by Django 4.1.6 on 2023-02-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='pharaphreased',
            field=models.CharField(choices=[('RUNNING', 'RUNNING'), ('NOT_DONE', 'NOT_DONE'), ('DONE', 'DONE')], default='NOT_DONE', max_length=10),
        ),
    ]
