# Generated by Django 4.1.6 on 2023-02-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_paraphrasedtext_created_alter_text_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='password',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
