# Generated by Django 4.1.6 on 2023-03-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_details_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='ProfileDict',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='user_details',
            name='profile',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
