# Generated by Django 4.1.6 on 2026-04-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user_details_profiledict_user_details_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='paraphrasedtext',
            name='mongo_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user_details',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='rest_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='session_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paraphrasedtext',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='ProfileDict',
            field=models.CharField(default='Profiles', max_length=255),
        ),
    ]
