# Generated by Django 4.1.6 on 2026-04-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_paraphrasedtext_mongo_id_user_details_last_used_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingStatsDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('processed', models.IntegerField(default=0)),
                ('success', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('total_time', models.FloatField(default=0.0)),
                ('avg_time', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingStatsHourly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('hour', models.IntegerField()),
                ('processed', models.IntegerField(default=0)),
                ('success', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('total_time', models.FloatField(default=0.0)),
                ('avg_time', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingStatsOverall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100, unique=True)),
                ('processed', models.BigIntegerField(default=0)),
                ('success', models.BigIntegerField(default=0)),
                ('failed', models.BigIntegerField(default=0)),
                ('total_time', models.FloatField(default=0.0)),
                ('avg_time', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='processingstatshourly',
            index=models.Index(fields=['file_name', 'date', 'hour'], name='app_process_file_na_f9bef2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='processingstatshourly',
            unique_together={('file_name', 'date', 'hour')},
        ),
        migrations.AddIndex(
            model_name='processingstatsdaily',
            index=models.Index(fields=['file_name', 'date'], name='app_process_file_na_a825a9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='processingstatsdaily',
            unique_together={('file_name', 'date')},
        ),
    ]
